#!/usr/bin/env python3
"""
Contract Accessors - unified, safe read-only helpers for execution contracts.

These functions provide a stable, typed API for all agents and utilities to query
the execution contract generated by the execution planner.

All accessors:
  - Return safe, typed defaults (empty lists/dicts) when keys are missing or malformed.
  - Never mutate the contract.
  - Gracefully handle null/unknown values in outcome/decision columns.

Compatibility:
  - Preserves legacy function names/constants for incremental migration.
"""

from typing import Dict, Any, List, Set
from src.utils.contract_validator import is_probably_path


# ============================================================================
# V4.1 CONTRACT GUARD – Enforcement of legacy field removal
# ============================================================================

# V4.1 Contract Version - Single source of truth
CONTRACT_VERSION_V41: str = "4.1"

# Legacy keys that MUST NOT appear in V4.1 contracts
LEGACY_KEYS: Set[str] = {
    "spec_extraction",
    "data_requirements",
    "role_runbooks",
    "validations",
    "quality_gates",
    "execution_plan",
    "artifact_schemas",
    "required_columns",
    "feature_availability",
    "decision_variables",
    "availability_summary",  # V4.1: Removed - no longer generated or consumed
}


def normalize_contract_version(version: Any) -> str:
    """
    Normalize contract version to V4.1 format.

    Accepts: "4.1", 4.1, 41, "41", 2, "2" -> returns "4.1"
    Returns CONTRACT_VERSION_V41 for any recognized version or None.
    """
    if version is None:
        return CONTRACT_VERSION_V41

    # Handle string versions
    if isinstance(version, str):
        v = version.strip().lower()
        if v in ("4.1", "v4.1", "41", "v41"):
            return CONTRACT_VERSION_V41
        # Legacy version 2 -> upgrade to 4.1
        if v in ("2", "2.0", "v2"):
            return CONTRACT_VERSION_V41

    # Handle numeric versions
    if isinstance(version, (int, float)):
        if version in (4.1, 41, 2, 2.0):
            return CONTRACT_VERSION_V41

    # Default: return V4.1
    return CONTRACT_VERSION_V41

# Allowed top-level keys in V4.1 contracts (for strict validation)
ALLOWED_TOP_LEVEL_KEYS_V41: Set[str] = {
    # Core identification
    "contract_version",
    "strategy_title",
    "business_objective",
    # Column specifications
    "available_columns",
    "canonical_columns",
    "derived_columns",
    "column_roles",
    "outcome_columns",
    "decision_columns",
    # Feature management
    "allowed_feature_sets",
    "feature_selectors",
    "feature_engineering_plan",
    # Requirements & validation
    "preprocessing_requirements",
    "validation_requirements",
    "artifact_requirements",
    "required_outputs",
    # Gates (V4.1 style)
    "qa_gates",
    "cleaning_gates",
    "reviewer_gates",
    # Runbooks (V4.1 style - direct, not nested under role_runbooks)
    "data_engineer_runbook",
    "ml_engineer_runbook",
    # Analysis & constraints
    "objective_analysis",
    "data_analysis",
    "execution_constraints",
    "segmentation_constraints",
    "optimization_specification",
    "leakage_execution_plan",
    # Policies & handling
    "reporting_policy",
    "decisioning_requirements",
    "outlier_policy",
    "omitted_columns_policy",
    "missing_columns_handling",
    "output_dialect",
    "visualization_requirements",
    # Data modes
    "data_limited_mode",
    "training_rows_rule",
    "scoring_rows_rule",
    "secondary_scoring_subset",
    "data_partitioning_notes",
    "split_spec",
    "n_train_rows",
    "n_test_rows",
    "n_total_rows",
    # Metadata
    "iteration_policy",
    "unknowns",
    "assumptions",
    "notes_for_engineers",
    # Ancillary (allowed but not required)
    "business_alignment",
    "compliance_checklist",
    "alignment_requirements",
    "evaluation_spec",  # V4.1 evaluation spec (not legacy)
}


def assert_no_legacy_keys(contract: Dict[str, Any], where: str = "") -> None:
    """
    Assert that the contract contains no legacy keys.

    Raises ValueError if any legacy key is found.

    Args:
        contract: The contract dictionary to validate.
        where: Optional context string for error messages (e.g., "execution_planner:final_contract").
    """
    if not isinstance(contract, dict):
        return

    found_legacy = LEGACY_KEYS & set(contract.keys())
    if found_legacy:
        location = f" at {where}" if where else ""
        raise ValueError(
            f"V4.1 Contract Violation{location}: Legacy keys found: {sorted(found_legacy)}. "
            f"These keys must be removed for V4.1 compliance."
        )


def warn_legacy_keys(contract: Dict[str, Any], where: str = "") -> List[str]:
    """
    Check for legacy keys and return a list of found keys (non-raising version).

    Args:
        contract: The contract dictionary to validate.
        where: Optional context string for logging.

    Returns:
        List of legacy keys found (empty if none).
    """
    if not isinstance(contract, dict):
        return []

    found_legacy = sorted(LEGACY_KEYS & set(contract.keys()))
    if found_legacy and where:
        print(f"WARNING: Legacy keys found at {where}: {found_legacy}")
    return found_legacy


def assert_only_allowed_v41_keys(contract: Dict[str, Any], strict: bool = False) -> List[str]:
    """
    Check that contract only contains allowed V4.1 keys.

    Args:
        contract: The contract dictionary to validate.
        strict: If True, raises ValueError on unknown keys. If False, just returns the list.

    Returns:
        List of unknown/unexpected keys found.
    """
    if not isinstance(contract, dict):
        return []

    contract_keys = set(contract.keys())
    unknown_keys = sorted(contract_keys - ALLOWED_TOP_LEVEL_KEYS_V41 - LEGACY_KEYS)

    if strict and unknown_keys:
        raise ValueError(
            f"V4.1 Contract Violation: Unknown keys found: {unknown_keys}. "
            f"Only allowed V4.1 keys are permitted."
        )

    return unknown_keys


def strip_legacy_keys(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return a new contract dict with all legacy keys removed.

    Does NOT mutate the original contract.

    Args:
        contract: The contract dictionary to clean.

    Returns:
        New dictionary with legacy keys removed.
    """
    if not isinstance(contract, dict):
        return {}

    return {k: v for k, v in contract.items() if k not in LEGACY_KEYS}


def get_available_columns(contract: Dict[str, Any]) -> List[str]:
    """
    Return the list of column names present in the dataset (before any transformations).
    
    Returns:
        List of column names available in the raw dataset.
    """
    if not isinstance(contract, dict):
        return []
    cols = contract.get("available_columns")
    if not isinstance(cols, list):
        return []
    return [str(c) for c in cols if c is not None]


def get_canonical_columns(contract: Dict[str, Any]) -> List[str]:
    """
    Return the canonical (required input) column names that agents must preserve.
    
    This is the source of truth for which columns are mandatory inputs.
    
    Returns:
        List of canonical column names.
    """
    if not isinstance(contract, dict):
        return []
    cols = contract.get("canonical_columns")
    if not isinstance(cols, list):
        return []
    return [str(c) for c in cols if c is not None]


def get_column_roles(contract: Dict[str, Any]) -> Dict[str, List[str]]:
    """
    Return the column_roles dictionary normalized to role -> list[str].
    
    Supports three input formats for robustness:
      A) dict role -> list[str]   (preferred V4.1 format)
      B) list[{"role": ..., "column": ...}]  (alternate list format)
      C) dict column -> role      (legacy V4.1 inverted format)
    
    Always returns: Dict[str, List[str]] mapping role -> columns.
    
    Returns:
        Dictionary mapping role names to lists of column names.
    """
    if not isinstance(contract, dict):
        return {}
    roles_raw = contract.get("column_roles")
    if not roles_raw:
        return {}
    
    # Format A: dict role -> list[str]
    if isinstance(roles_raw, dict):
        first_val = next(iter(roles_raw.values()), None) if roles_raw else None
        if isinstance(first_val, list):
            # Already in preferred format
            result: Dict[str, List[str]] = {}
            for role, cols in roles_raw.items():
                if isinstance(cols, list):
                    result[str(role)] = [str(c) for c in cols if c is not None]
            return result
        elif isinstance(first_val, dict):
            # Format C with metadata: column -> {role: ..., ...}
            result = {}
            for col, meta in roles_raw.items():
                if isinstance(meta, dict):
                    role = meta.get("role")
                    if role:
                        result.setdefault(str(role), []).append(str(col))
            return result
        elif isinstance(first_val, str) or first_val is None:
            # Format C: column -> role (inverted)
            result = {}
            for col, role in roles_raw.items():
                if isinstance(role, str):
                    result.setdefault(role, []).append(str(col))
            return result
    
    # Format B: list[{"role": ..., "column": ...}]
    if isinstance(roles_raw, list):
        result = {}
        for item in roles_raw:
            if isinstance(item, dict):
                role = item.get("role")
                col = item.get("column") or item.get("name")
                if role and col:
                    result.setdefault(str(role), []).append(str(col))
        return result
    
    return {}


def get_outcome_columns(contract: Dict[str, Any]) -> List[str]:
    """
    Return the list of outcome column names.

    Priority:
      1. contract["outcome_columns"] if provided
      2. column_roles["outcome"] if exists
      3. validation_requirements.params (target, label_column, outcome_column)
      4. objective_analysis if contains target-related info
      5. Empty list if nothing found

    Returns:
        List of outcome column names. Empty if not specified or 'unknown'.
    """
    if not isinstance(contract, dict):
        return []

    explicit = contract.get("outcome_columns")
    if isinstance(explicit, list) and explicit:
        return [str(v) for v in explicit if v and str(v).lower() != "unknown"]
    if isinstance(explicit, str) and explicit.lower() != "unknown":
        return [explicit]

    # First: try column_roles["outcome"]
    roles = get_column_roles(contract)
    outcome_cols_raw = roles.get("outcome", [])
    if isinstance(outcome_cols_raw, str):
        outcome_cols = [outcome_cols_raw]
    elif isinstance(outcome_cols_raw, list):
        outcome_cols = outcome_cols_raw
    else:
        outcome_cols = []
    if outcome_cols:
        return [str(c) for c in outcome_cols if c and str(c).lower() != "unknown"]
    # Universal fallback: many contracts express supervised targets as `target` role.
    for alias in ("target", "label", "response", "y"):
        alias_cols_raw = roles.get(alias, [])
        if isinstance(alias_cols_raw, str):
            alias_cols = [alias_cols_raw]
        elif isinstance(alias_cols_raw, list):
            alias_cols = alias_cols_raw
        else:
            alias_cols = []
        if alias_cols:
            return [str(c) for c in alias_cols if c and str(c).lower() != "unknown"]

    # Fallback: validation_requirements.params
    val_req = contract.get("validation_requirements")
    if isinstance(val_req, dict):
        # Preferred direct fields under validation_requirements
        for key in ("target_column", "outcome_column", "target", "outcome", "label"):
            val = val_req.get(key)
            if isinstance(val, str) and val.strip() and val.lower() != "unknown":
                return [val.strip()]
            if isinstance(val, list):
                result = [str(v).strip() for v in val if v and str(v).lower() != "unknown"]
                if result:
                    return result

        # Legacy nested fields under validation_requirements.params
        params = val_req.get("params", {})
        if isinstance(params, dict):
            for key in ("target", "target_column", "label_column", "outcome_column", "y_column"):
                val = params.get(key)
                if isinstance(val, str) and val.strip() and val.lower() != "unknown":
                    return [val.strip()]
                elif isinstance(val, list):
                    result = [str(v).strip() for v in val if v and str(v).lower() != "unknown"]
                    if result:
                        return result

    # Fallback: objective_analysis
    obj_analysis = contract.get("objective_analysis")
    if isinstance(obj_analysis, dict):
        # Check for target/outcome fields
        for key in ("target_column", "outcome_column", "target", "outcome"):
            val = obj_analysis.get(key)
            if val:
                if isinstance(val, list):
                    return [str(v) for v in val if v and str(v).lower() != "unknown"]
                elif isinstance(val, str) and val.lower() != "unknown":
                    return [val]

    return []


def get_decision_columns(contract: Dict[str, Any]) -> List[str]:
    """
    Return the list of decision column names.
    
    Returns:
        List of decision column names. Empty if not specified.
    """
    if not isinstance(contract, dict):
        return []

    explicit = contract.get("decision_columns")
    if isinstance(explicit, list) and explicit:
        return [str(v) for v in explicit if v and str(v).lower() != "unknown"]
    if isinstance(explicit, str) and explicit.lower() != "unknown":
        return [explicit]
    
    # Use column_roles["decision"]
    roles = get_column_roles(contract)
    decision_cols = roles.get("decision", [])
    return [c for c in decision_cols if c and c.lower() != "unknown"]


def get_derived_column_names(contract: Dict[str, Any]) -> List[str]:
    """
    Return names of derived columns (columns created during preprocessing/feature engineering).
    
    Combines:
      - contract.get("derived_columns")
      - contract.get("feature_engineering_plan", {}).get("derived_columns")
    
    Accepts list[str] or list[dict{name/...}] and normalizes to unique list[str].
    
    Returns:
        List of derived column names (unique, order preserved).
    """
    if not isinstance(contract, dict):
        return []
    
    def _extract_names(source: Any) -> List[str]:
        if not source:
            return []
        if isinstance(source, list):
            names = []
            for item in source:
                if isinstance(item, str):
                    names.append(item)
                elif isinstance(item, dict):
                    name = item.get("name") or item.get("column")
                    if name:
                        names.append(str(name))
            return names
        return []
    
    derived = []
    
    # From top-level derived_columns
    derived.extend(_extract_names(contract.get("derived_columns")))
    
    # From feature_engineering_plan.derived_columns
    feat_plan = contract.get("feature_engineering_plan")
    if isinstance(feat_plan, dict):
        derived.extend(_extract_names(feat_plan.get("derived_columns")))
        derived.extend(_extract_names(feat_plan.get("features")))
    
    # From preprocessing_requirements transformations
    prep_reqs = contract.get("preprocessing_requirements")
    if isinstance(prep_reqs, dict):
        transformations = prep_reqs.get("transformations")
        if isinstance(transformations, list):
            for t in transformations:
                if isinstance(t, dict):
                    output_col = t.get("output_column")
                    if output_col and isinstance(output_col, str):
                        derived.append(output_col)
    
    # Deduplicate preserving order
    seen = set()
    result = []
    for name in derived:
        if name not in seen:
            seen.add(name)
            result.append(name)
    return result


def get_artifact_requirements(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return artifact_requirements section defining required outputs.
    
    Example structure:
    {
      "required_files": ["scored_rows.csv", "model_summary.json"],
      "required_plots": ["confusion_matrix.png"],
      "file_schemas": {...}
    }
    
    Returns:
        Dictionary with artifact requirements.
    """
    if not isinstance(contract, dict):
        return {"required_files": [], "required_plots": []}
    artifacts = contract.get("artifact_requirements")
    if not isinstance(artifacts, dict):
        return {"required_files": [], "required_plots": []}
    return artifacts


_GATE_NAME_KEYS = ("name", "id", "gate", "metric", "check", "rule", "title", "label")
_GATE_PARAM_KEYS = (
    "metric",
    "check",
    "rule",
    "threshold",
    "target",
    "min",
    "max",
    "operator",
    "direction",
    "condition",
)
_GATE_EXTRA_KEYS = ("condition", "evidence_required", "action_if_fail")


def _extract_gate_name(gate: Dict[str, Any]) -> str:
    for key in _GATE_NAME_KEYS:
        value = gate.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _normalize_gate_list(raw_gates: Any) -> List[Dict[str, Any]]:
    if not isinstance(raw_gates, list):
        return []

    normalized: List[Dict[str, Any]] = []
    seen: set[str] = set()
    for gate in raw_gates:
        if isinstance(gate, str):
            name = gate.strip()
            if not name:
                continue
            key = name.lower()
            if key in seen:
                continue
            seen.add(key)
            normalized.append({"name": name, "severity": "HARD", "params": {}})
            continue

        if not isinstance(gate, dict):
            continue

        name = _extract_gate_name(gate)
        if not name:
            continue
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)

        severity = gate.get("severity")
        required = gate.get("required")
        if severity is None and required is not None:
            severity = "HARD" if bool(required) else "SOFT"
        severity = str(severity).upper() if severity else "HARD"
        if severity not in {"HARD", "SOFT"}:
            severity = "HARD"

        params = gate.get("params")
        if not isinstance(params, dict):
            params = {}
        for param_key in _GATE_PARAM_KEYS:
            if param_key in gate and param_key not in params:
                params[param_key] = gate.get(param_key)

        entry: Dict[str, Any] = {
            "name": name,
            "severity": severity,
            "params": params,
        }
        for extra_key in _GATE_EXTRA_KEYS:
            if extra_key in gate:
                entry[extra_key] = gate.get(extra_key)
        normalized.append(entry)
    return normalized


def get_qa_gates(contract: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Return the list of QA gate specifications.
    
    Returns:
        List of QA gate objects.
    """
    if not isinstance(contract, dict):
        return []
    return _normalize_gate_list(contract.get("qa_gates"))


def get_cleaning_gates(contract: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Return the list of cleaning gate specifications.

    Returns:
        List of cleaning gate objects.
    """
    if not isinstance(contract, dict):
        return []
    return _normalize_gate_list(contract.get("cleaning_gates"))


def get_reviewer_gates(contract: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Return the list of reviewer gate specifications.
    
    Returns:
        List of reviewer gate objects.
    """
    if not isinstance(contract, dict):
        return []
    return _normalize_gate_list(contract.get("reviewer_gates"))


def get_data_engineer_runbook(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return the data_engineer_runbook section.
    
    Returns:
        Dictionary containing data engineer instructions.
    """
    if not isinstance(contract, dict):
        return {}
    runbook = contract.get("data_engineer_runbook")
    if not isinstance(runbook, dict):
        return {}
    return runbook


def get_ml_engineer_runbook(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return the ml_engineer_runbook section.
    
    Returns:
        Dictionary containing ML engineer instructions.
    """
    if not isinstance(contract, dict):
        return {}
    runbook = contract.get("ml_engineer_runbook")
    if not isinstance(runbook, dict):
        return {}
    return runbook


def get_preprocessing_requirements(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return preprocessing_requirements section.
    
    Returns:
        Dictionary with preprocessing specifications.
    """
    if not isinstance(contract, dict):
        return {}
    prep = contract.get("preprocessing_requirements")
    if not isinstance(prep, dict):
        return {}
    return prep


def get_outlier_policy(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return outlier_policy section when provided by the execution contract.

    This policy is optional and contract-driven. If absent or malformed, callers
    must treat it as disabled and avoid deterministic assumptions.

    Returns:
        Dictionary with outlier policy fields (possibly empty).
    """
    if not isinstance(contract, dict):
        return {}
    policy = contract.get("outlier_policy")
    if not isinstance(policy, dict):
        return {}
    return policy


def get_validation_requirements(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return validation_requirements section.
    
    Returns:
        Dictionary with validation specifications.
    """
    if not isinstance(contract, dict):
        return {}
    validation = contract.get("validation_requirements")
    if not isinstance(validation, dict):
        return {}
    return validation


def get_optimization_specification(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return optimization_specification section.
    
    Returns:
        Dictionary with optimization specifications.
    """
    if not isinstance(contract, dict):
        return {}
    opt = contract.get("optimization_specification")
    if not isinstance(opt, dict):
        return {}
    return opt


def get_segmentation_constraints(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return segmentation_constraints section.
    
    Returns:
        Dictionary with segmentation specifications.
    """
    if not isinstance(contract, dict):
        return {}
    seg = contract.get("segmentation_constraints")
    if not isinstance(seg, dict):
        return {}
    return seg


def get_execution_constraints(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return execution_constraints section.
    
    Returns:
        Dictionary with execution constraints.
    """
    if not isinstance(contract, dict):
        return {}
    constraints = contract.get("execution_constraints")
    if not isinstance(constraints, dict):
        return {}
    return constraints


def get_objective_analysis(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return objective_analysis section.
    
    Returns:
        Dictionary with objective analysis.
    """
    if not isinstance(contract, dict):
        return {}
    obj = contract.get("objective_analysis")
    if not isinstance(obj, dict):
        return {}
    return obj


def get_feature_engineering_plan(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return feature_engineering_plan section.
    
    Returns:
        Dictionary with feature engineering plan.
    """
    if not isinstance(contract, dict):
        return {}
    plan = contract.get("feature_engineering_plan")
    if not isinstance(plan, dict):
        return {}
    return plan


def get_leakage_execution_plan(contract: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return leakage_execution_plan section.
    
    Returns:
        Dictionary with leakage audit plan.
    """
    if not isinstance(contract, dict):
        return {}
    plan = contract.get("leakage_execution_plan")
    if not isinstance(plan, dict):
        return {}
    return plan


def get_required_outputs(contract: Dict[str, Any]) -> List[str]:
    """
    Return list of required output files from contract outputs and artifact requirements.
    
    Combines:
      - artifact_requirements.required_files
      - artifact_requirements.required_plots
      - artifact_requirements.visual_requirements.items (when required)
      - visualization_requirements.required_plots
      - required_outputs (top-level)
    
    Normalizes paths:
      - Backslash to forward slash
      - Known basenames (metrics.json, etc.) get data/ prefix
    
    Returns:
        Unique list of required output paths (normalized).
    """
    import os
    import re
    
    def _normalize_path(path: str) -> str:
        """Normalize separators while preserving contract-declared relative paths."""
        if not path:
            return path
        path = path.replace("\\", "/").strip()
        return path.lstrip("/")

    def _slug(value: Any, fallback: str) -> str:
        token = re.sub(r"[^0-9a-zA-Z]+", "_", str(value or "")).strip("_").lower()
        return token or fallback

    def _extract_candidate(item: Any, *, allow_name_fallback: bool = True) -> str:
        if not item:
            return ""
        if isinstance(item, dict):
            for key in (
                "path",
                "output_path",
                "output",
                "artifact",
                "file",
                "filename",
                "expected_filename",
            ):
                value = item.get(key)
                if value:
                    return str(value)
            if allow_name_fallback:
                for key in ("plot_id", "id", "name", "title"):
                    value = item.get(key)
                    if value:
                        return str(value)
            return ""
        return str(item)

    def _normalize_plot_path(candidate: Any, outputs_dir: str, fallback: str) -> str:
        """
        Normalize plot artifact paths while preserving explicit filenames/extensions.
        Important: never transform "name.png" into "name_png.png".
        """
        base_dir = str(outputs_dir or "static/plots").replace("\\", "/").rstrip("/")
        if not base_dir:
            base_dir = "static/plots"
        raw = str(candidate or "").strip().replace("\\", "/")
        if not raw:
            raw = fallback

        # Preserve wildcard plot contracts (e.g., "*.png", "static/plots/*.png").
        if any(tok in raw for tok in ("*", "?", "[")):
            if not os.path.isabs(raw) and "/" not in raw:
                return f"{base_dir}/{raw}"
            return raw

        is_abs = os.path.isabs(raw)
        dirname, filename = os.path.split(raw)
        filename = filename or fallback

        stem, ext = os.path.splitext(filename)
        safe_stem = _slug(stem or filename, fallback)
        safe_ext = str(ext or "").lower().strip()
        if not safe_ext:
            safe_ext = ".png"
        elif not safe_ext.startswith("."):
            safe_ext = f".{safe_ext}"

        normalized_filename = f"{safe_stem}{safe_ext}"
        normalized = f"{dirname.rstrip('/')}/{normalized_filename}" if dirname else normalized_filename
        if not is_abs and "/" not in normalized:
            normalized = f"{base_dir}/{normalized}"
        return normalized
    
    if not isinstance(contract, dict):
        return []
    
    outputs = []

    def _append_if_path(path: Any) -> None:
        text = str(path or "").strip()
        if text and is_probably_path(text):
            outputs.append(text)
    
    # From artifact_requirements
    artifacts = get_artifact_requirements(contract)
    visual_cfg = artifacts.get("visual_requirements") if isinstance(artifacts.get("visual_requirements"), dict) else {}
    visual_outputs_dir = (
        visual_cfg.get("outputs_dir")
        or artifacts.get("visual_outputs_dir")
        or artifacts.get("outputs_dir")
        or "static/plots"
    )
    required_files = artifacts.get("required_files")
    if isinstance(required_files, list):
        for entry in required_files:
            _append_if_path(_extract_candidate(entry, allow_name_fallback=False))
    required_plots = artifacts.get("required_plots")
    if isinstance(required_plots, list):
        for idx, entry in enumerate(required_plots, start=1):
            candidate = _extract_candidate(entry)
            normalized = _normalize_plot_path(candidate, str(visual_outputs_dir), f"required_plot_{idx}")
            _append_if_path(normalized)

    # From artifact_requirements.visual_requirements (only required items)
    if isinstance(visual_cfg, dict):
        visual_enabled = bool(visual_cfg.get("enabled", True))
        visual_required = bool(visual_cfg.get("required"))
        visual_items = visual_cfg.get("items") if isinstance(visual_cfg.get("items"), list) else []
        if visual_enabled and visual_items:
            for idx, entry in enumerate(visual_items, start=1):
                if not isinstance(entry, dict):
                    continue
                item_required = entry.get("required")
                if not visual_required and item_required is not True:
                    continue
                candidate = _extract_candidate(entry, allow_name_fallback=True)
                normalized = _normalize_plot_path(candidate, str(visual_outputs_dir), f"visual_item_{idx}")
                _append_if_path(normalized)

    # From top-level visualization_requirements.required_plots
    visualization_requirements = (
        contract.get("visualization_requirements") if isinstance(contract.get("visualization_requirements"), dict) else {}
    )
    if isinstance(visualization_requirements, dict):
        top_visual_required = bool(visualization_requirements.get("required")) or bool(visual_cfg.get("required"))
        if not top_visual_required:
            top_required_plots = []
        else:
            top_required_plots = visualization_requirements.get("required_plots")
        top_outputs_dir = visualization_requirements.get("outputs_dir") or visual_outputs_dir
        if isinstance(top_required_plots, list):
            for idx, entry in enumerate(top_required_plots, start=1):
                candidate = _extract_candidate(entry, allow_name_fallback=True)
                normalized = _normalize_plot_path(candidate, str(top_outputs_dir), f"viz_required_plot_{idx}")
                _append_if_path(normalized)
    
    # From top-level required_outputs
    top_level = contract.get("required_outputs")
    if isinstance(top_level, list):
        for entry in top_level:
            if isinstance(entry, dict):
                candidate = entry.get("path")
                _append_if_path(candidate if isinstance(candidate, str) else "")
            else:
                _append_if_path(entry)
    
    # Normalize and deduplicate
    seen = set()
    result = []
    for o in outputs:
        norm = _normalize_path(o)
        if norm and norm not in seen:
            seen.add(norm)
            result.append(norm)
    return result


def _infer_kind_from_path(path: str) -> str:
    """Infer deliverable kind from its file path.

    Canonical location for kind inference — used as fallback when deliverables
    lack an explicit 'kind' field.  New contracts SHOULD always have explicit kind.
    """
    lower = str(path).lower()
    if "plots" in lower or lower.endswith((".png", ".jpg", ".jpeg", ".svg")):
        return "plot"
    if lower.endswith(".csv"):
        if "submission" in lower:
            return "submission"
        return "dataset"
    if lower.endswith(".json"):
        if "metrics" in lower:
            return "metrics"
        if "weights" in lower:
            return "weights"
        if "alignment" in lower or "report" in lower:
            return "report"
        return "json"
    return "artifact"


def _infer_owner_from_path(path: str) -> str:
    """Infer which engineer owns a deliverable based on its path.

    Returns "data_engineer" for cleaning-related artifacts, "ml_engineer" otherwise.
    """
    lower = (path or "").lower()
    if any(tok in lower for tok in ("cleaned_data", "cleaning_manifest")):
        return "data_engineer"
    return "ml_engineer"


def get_required_outputs_by_owner(contract: Dict[str, Any], owner: str) -> List[str]:
    """Return required output paths filtered by owner.

    Supports both List[str] (legacy) and List[dict] formats for required_outputs.
    When items lack an explicit 'owner' field, uses _infer_owner_from_path as fallback.
    """
    if not isinstance(contract, dict):
        return []
    raw = contract.get("required_outputs")
    if not isinstance(raw, list) or not raw:
        return []
    result: List[str] = []
    for item in raw:
        if isinstance(item, dict):
            path = item.get("path") or ""
            item_owner = item.get("owner") or _infer_owner_from_path(path)
            if item_owner == owner:
                result.append(path)
        elif isinstance(item, str):
            if _infer_owner_from_path(item) == owner:
                result.append(item)
    return result


def get_deliverables(contract: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Return canonical deliverables from the contract.

    Source of truth: ``spec_extraction.deliverables`` (rich dicts).
    Fallback: builds deliverables from ``required_outputs`` (legacy).
    """
    if not isinstance(contract, dict):
        return []
    spec = contract.get("spec_extraction")
    if isinstance(spec, dict):
        deliverables = spec.get("deliverables")
        if isinstance(deliverables, list) and deliverables:
            return [d for d in deliverables if isinstance(d, dict) and d.get("path")]
    # Fallback: build from required_outputs
    raw = contract.get("required_outputs", [])
    if not isinstance(raw, list):
        return []
    result: List[Dict[str, Any]] = []
    for item in raw:
        if isinstance(item, dict):
            path = item.get("path") or ""
            result.append({
                "path": path,
                "required": bool(item.get("required", True)),
                "kind": item.get("kind") or _infer_kind_from_path(path),
                "owner": item.get("owner") or _infer_owner_from_path(path),
                "description": item.get("description", ""),
            })
        elif isinstance(item, str) and item.strip():
            result.append({
                "path": item,
                "required": True,
                "kind": _infer_kind_from_path(item),
                "owner": _infer_owner_from_path(item),
                "description": "",
            })
    return result


def get_deliverables_by_owner(contract: Dict[str, Any], owner: str) -> List[Dict[str, Any]]:
    """Return deliverables filtered by owner."""
    return [d for d in get_deliverables(contract) if d.get("owner") == owner]
